name: Update Submodules

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: 'master'

      - name: Update Submodules
        run: |
          git config --global user.email "20642596+sakarie9@users.noreply.github.com"
          git config --global user.name "Sakari"
          git submodule update --remote --recursive
          git add -v .
          git diff-index --quiet HEAD || git commit -m "Update Submodules"
          git push
